# CodeLoom Codecov Configuration

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  rust:
    paths:
      - engine/
      - cli/
    carryforward: true
  zig:
    paths:
      - core/
    carryforward: true

ignore:
  - "tests/"
  - "benches/"
  - "**/tests/**"
  - "**/*_test.rs"
