/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for packing a repository */
export interface PackOptions {
  /** Output format: "xml", "markdown", or "json" */
  format?: string
  /** Target model: "claude", "gpt-4o", "gpt-4", "gemini", or "llama" */
  model?: string
  /** Compression level: "none", "minimal", "balanced", "aggressive", "extreme", "semantic" */
  compression?: string
  /** Token budget for repository map */
  mapBudget?: number
  /** Maximum number of symbols in map */
  maxSymbols?: number
  /** Skip security scanning */
  skipSecurity?: boolean
}
/** Statistics from scanning a repository */
export interface ScanStats {
  /** Repository name */
  name: string
  /** Total number of files */
  totalFiles: number
  /** Total lines of code */
  totalLines: number
  /** Total tokens for target model */
  totalTokens: number
  /** Primary language */
  primaryLanguage?: string
  /** Language breakdown */
  languages: Array<LanguageStat>
  /** Number of security findings */
  securityFindings: number
}
/** Statistics for a single language */
export interface LanguageStat {
  /** Language name */
  language: string
  /** Number of files */
  files: number
  /** Total lines */
  lines: number
  /** Percentage of codebase */
  percentage: number
}
/**
 * Pack a repository into optimized LLM context
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `options` - Optional packing options
 *
 * # Returns
 * Formatted repository context as a string
 *
 * # Example
 * ```javascript
 * const { pack } = require('@codeloom/node');
 *
 * const context = pack('./my-repo', {
 *   format: 'xml',
 *   model: 'claude',
 *   compression: 'balanced',
 *   map_budget: 2000
 * });
 * ```
 */
export declare function pack(path: string, options?: PackOptions | undefined | null): string
/**
 * Scan a repository and return statistics
 *
 * # Arguments
 * * `path` - Path to repository root
 * * `model` - Optional target model (default: "claude")
 *
 * # Returns
 * Repository statistics
 *
 * # Example
 * ```javascript
 * const { scan } = require('@codeloom/node');
 *
 * const stats = scan('./my-repo', 'claude');
 * console.log(`Total files: ${stats.total_files}`);
 * console.log(`Total tokens: ${stats.total_tokens}`);
 * ```
 */
export declare function scan(path: string, model?: string | undefined | null): ScanStats
/**
 * Count tokens in text for a specific model
 *
 * # Arguments
 * * `text` - Text to tokenize
 * * `model` - Optional model name (default: "claude")
 *
 * # Returns
 * Token count
 *
 * # Example
 * ```javascript
 * const { countTokens } = require('@codeloom/node');
 *
 * const count = countTokens('Hello, world!', 'claude');
 * console.log(`Tokens: ${count}`);
 * ```
 */
export declare function countTokens(text: string, model?: string | undefined | null): number
/** CodeLoom class for advanced usage */
export declare class CodeLoom {
  /**
   * Create a new CodeLoom instance
   *
   * # Arguments
   * * `path` - Path to repository root
   * * `model` - Optional model name (default: "claude")
   */
  constructor(path: string, model?: string | undefined | null)
  /** Get repository statistics */
  getStats(): ScanStats
  /**
   * Generate a repository map
   *
   * # Arguments
   * * `budget` - Token budget (default: 2000)
   * * `max_symbols` - Maximum symbols (default: 50)
   */
  generateMap(budget?: number | undefined | null, maxSymbols?: number | undefined | null): string
  /** Pack repository with specific options */
  pack(options?: PackOptions | undefined | null): string
  /** Check for security issues */
  securityScan(): Array<string>
}
