# Example GitHub Actions workflow for CodeLoom WASM
# Copy this to .github/workflows/wasm.yml in the root repository

name: WASM Build and Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'bindings/wasm/**'
      - 'engine/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'bindings/wasm/**'
      - 'engine/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [web, nodejs, bundler]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: bindings/wasm/target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build WASM (${{ matrix.target }})
      working-directory: bindings/wasm
      run: |
        case ${{ matrix.target }} in
          web)
            wasm-pack build --target web --out-dir pkg-web
            ;;
          nodejs)
            wasm-pack build --target nodejs --out-dir pkg-node
            ;;
          bundler)
            wasm-pack build --target bundler --out-dir pkg
            ;;
        esac

    - name: Check package size
      working-directory: bindings/wasm
      run: |
        case ${{ matrix.target }} in
          web)
            du -sh pkg-web/codeloom_wasm_bg.wasm
            ;;
          nodejs)
            du -sh pkg-node/codeloom_wasm_bg.wasm
            ;;
          bundler)
            du -sh pkg/codeloom_wasm_bg.wasm
            ;;
        esac

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasm-${{ matrix.target }}
        path: bindings/wasm/pkg*

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Run unit tests
      working-directory: bindings/wasm
      run: cargo test

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Run WASM tests (Firefox)
      working-directory: bindings/wasm
      run: wasm-pack test --headless --firefox

  test-node:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: wasm-nodejs
        path: bindings/wasm/pkg-node

    - name: Run Node.js example
      working-directory: bindings/wasm
      run: node demo/node-example.js

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy
        override: true

    - name: Check formatting
      working-directory: bindings/wasm
      run: cargo fmt -- --check

    - name: Run clippy
      working-directory: bindings/wasm
      run: cargo clippy -- -D warnings

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      working-directory: bindings/wasm
      run: cargo audit

  publish:
    runs-on: ubuntu-latest
    needs: [build, test, test-node, lint]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/wasm-v')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build all targets
      working-directory: bindings/wasm
      run: ./build.sh

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish to npm
      working-directory: bindings/wasm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: CodeLoom WASM ${{ github.ref }}
        draft: false
        prerelease: false
